apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: # deprecated in standalone Kustomize since v3, use resources
  - ../../../base

components:
  - ../../shared/readiness
  - ../../shared/liveness

patchesStrategicMerge:
  - env.yaml