apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.appName }}
  name: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  strategy: {}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - image: peteby/{{ .Values.appName }}
        name: {{ .Values.appName }}
        env:
          - name: env
            value: dev
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        # If the hook doesn’t receive UP status for readiness,
        # then traffic won’t be routed to that port. The pod won’t be restart.
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: http
          initialDelaySeconds: 10
          timeoutSeconds: 3
          periodSeconds: 5
          failureThreshold: 3
        # If HTTP GET request to liveness doesn’t receive UP status in the timing conditions above,
        # the pod will restart.
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness # /alive
            port: http
          initialDelaySeconds: 10 # means that send the GET request after waiting 10 seconds.
          timeoutSeconds: 3 # means that if there is no response within 3 seconds, time out.
          periodSeconds: 5 # means that check by sending this request every 5 seconds.
          failureThreshold: 3 # means that let it fail 3 times.
        lifecycle:
          preStop:
            httpGet:
              path: /stopping
              port: http
        resources: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 15
status: {}
