apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: demo-rest-service
build:
  artifacts:
  - image: peteby/demo-rest-service
    context: .
    jib:
      project: com.axamit.springboot:demo-rest-service
deploy:
  kustomize:
    paths: ["k8s/kustomize/templates/base"]
profiles:
  - name: local
    deploy:
      kustomize:
        paths: [ "k8s/demo-rest-service/templates/base" ]
  - name: dev
    deploy:
      kustomize:
        paths: [ "k8s/demo-rest-service/templates/overlays/environments/dev" ]
# Port forwarding section is optional
portForward:
  - resourceType: service
    resourceName: demo-rest-service
    port: 8080
    localPort: 80