apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/version: {{ .Values.appVersion }}
    app: {{ .Values.appName }}
  name: {{ .Values.appName }}
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ .Values.appName }}
  type: ClusterIP
status:
  loadBalancer: {}
