apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patchesStrategicMerge:
  - |-
    apiVersion: v1
    kind: Service
    metadata:
      namespace: {{ .Values.namespace }}
      name: {{ .Values.appName }}
    spec:
      type: LoadBalancer
