apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.appName }}
spec:
  template:
    spec:
      containers:
        - name: {{ .Values.appName }}
          # If the hook doesn't receive UP status for readiness,
          # then traffic won't be routed to that port. The pod won't be restart.
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 20
            timeoutSeconds: 3
            periodSeconds: 5
            failureThreshold: 3